### ISSUE TITLE
Некорректное отображение списка эпизодов

### ISSUE THREAD

**Issue by Pachini** [a-ignatov-parc/movian-soap4.me#2]
Некорректное отображение списка эпизодов если в настройках сайта включены субтитры, на скришоте ниже сезон в котором одинаковое количество эпизодов с сабами и озвучкой, но в итоге с сабами показывает 11 эпизодов и всего 2 озвученных.

![2016-03-15 10 39 26](https://cloud.githubusercontent.com/assets/1598070/13770769/72b88aba-ea9a-11e5-8777-f6938f9aa51d.png)

Оптимально добавить в настройках селектор:
- показывать все эпизоды (субтитры и озвучка вперемешку)
- только субтитры (если нет эпизода с сабами, показывать эпизоды с озвучкой)
- только озученные

**Comment by a-ignatov-parc** [comment]
Изучу этот вопрос :+1:

**Comment by a-ignatov-parc** [comment]
@Pachini добрался до описанной проблемы, но к сожалению я ничего не могу с этим сделать. После включения опции в настройках сайта api соупа выдает только те данные что видно в плеере. Без какой-то возможности получить какие-то другие данные =(

**Comment by a-ignatov-parc** [comment]
Если появится какая-то новая информация я открою этот ишью

**Comment by Pachini** [comment]
Есть недопонимание :)

При включении субтитров на сайте в настройках, апи начинает выдавать все доступные эпизоды. А дальше уже проблема клиента, он не правильно отображает полученный список

**Comment by a-ignatov-parc** [comment]
[Тут](https://gist.github.com/a-ignatov-parc/dde41073624393732268) можно увидеть ответ от api соупа по запросу на ресурс сериала (https://soap4.me/api/episodes/547). Проблема, как видно, не на стороне клиента. Ну если только я не ошибся в ресурсе. Но именно его мне скинула команда соупа в доке `¯\_(ツ)_/¯`

**Comment by a-ignatov-parc** [comment]
А нет. Это мой косяк )

**Comment by a-ignatov-parc** [comment]
Нашел проблему. Займусь ей

**Comment by a-ignatov-parc** [comment]
@Pachini добавил версию 1.0.7. Она доступна для бета тестирования. Буду признателен если поможешь с проверкой :+1:

**Comment by Pachini** [comment]
Всё ок, работает. Спасибо!

**Comment by a-ignatov-parc** [comment]
Отлично. Тогда публикую и после апрува станет доступно всем
