### ISSUE TITLE
UP если несложно и есть время

### ISSUE THREAD

**Issue by Buksa** [a-ignatov-parc/movian-soap4.me#6]
возможно ли обновить под последний node/gulp ?

**Comment by a-ignatov-parc** [comment]
@Buksa перед тем как дать ответ я бы хотел поинтересоваться зачем вам это нужно? Интересуюсь этим вопросом потому что свободного времени крайне мало и не хотелось бы его тратить в пустую на проект 7 летней давности 🙂

**Comment by Buksa** [comment]
да так чтоб разговор начать :) ну а так если время нет то не надо chatgpt мне в помощь. просто на 8 и старом gulp запустится точно. просто интересно было глянуть как оно сделано.  просто не видел такого в основном плагины просто написаны а у тя gulp с babeljs. ну и еще пара тоже интересных https://github.com/facferreira/movian-plugin-dailymotion ts  и https://github.com/facferreira/movian-plugin-trakt просто я далек от программирования и было интересно как оно написано если подскажешь что почитать было бы не плохо а так спасибо за ответ.

**Comment by a-ignatov-parc** [comment]
> ну а так если время нет то не надо

Понял, спасибо за ответ. Тогда закрываю этот issue 👍 

> просто на 8 и старом gulp запустится точно

Да, на `node@8` точно будет работать.

> просто не видел такого в основном плагины просто написаны а у тя gulp с babeljs

Тут все просто
1. Babel использовался для downleveling es5 синтаксиса в старую версию JS, которая на то время поддерживалась в node.js и Movian.
2. Gulp во времена написания плагина был стандартом де-факто для автоматизации процесса сборки 🙂 

Полагаю ни то, ни другое сейчас уже не актуально для разработки плагинов для Movian.

> если подскажешь что почитать было бы не плохо

К сожалению ни по программированию, ни по разработке плагинов для Movian ничего не смогу подсказать так как я далек от обучения и от текущего состояния Movian тоже.
